-- Create application non-superuser role
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ert_app') THEN
    CREATE ROLE ert_app LOGIN PASSWORD 'ert_apppass' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
  END IF;
END$$;

GRANT CONNECT ON DATABASE ert_dev TO ert_app;
\connect ert_dev
GRANT USAGE ON SCHEMA public TO ert_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ert_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ert_app;
