version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    # labels removed ("dependencies", "backend") because they do not yet exist in the repo.
    # Re-add after creating them under Settings > Labels.
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types: ["minor", "patch"]
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    # labels removed ("dependencies", "frontend") until labels are created.
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types: ["minor", "patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # labels removed ("dependencies", "ci") until created.
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
